#!/bin/bash

while  read -r line; do
  if [[ $line != '' && $line != \#* ]]; then
    while IFS=, read name ipaddress group execute
    do
      echo "Name: $name, IP: $ipaddress, Group: $group, Execute:$execute"

      if $execute ; then
        bash ./scripts/create_machine -n $name -a $ipaddress -g $group -x
      else
        bash ./scripts/create_machine -n $name -a $ipaddress -g $group
      fi

    done <<< $line
  fi
done < machines.csv
