#!/bin/bash

while  read -r line; do
  if [[ $line != '' && $line != \#* ]]; then
    while IFS=, read name ipaddress group execute
    do
      bash ./scripts/remove_machine -n $name -a $ipaddress
    done <<< $line
  fi
done < remove_machines.csv
